# Generated by Django 2.1.5 on 2021-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20210707_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='athletes',
        ),
        migrations.AddField(
            model_name='athlete',
            name='familys',
            field=models.ManyToManyField(to='athletes.Family'),
        ),
    ]
