# Generated by Django 2.1.5 on 2021-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20210707_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
